version: '2'

services:
  experiments_knowledge_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: experiments_knowledge_service
    environment:
      - NODE_EVN=prod
    image: filiprydzi/experiments_knowledge_service:0.8.3
    ports:
    - 9000:9000
    links:
    - mongodb
    - neo4j
    depends_on:
    - mongodb
    - neo4j
    command: start-prod

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
    - MONGO_LOG_DIR=/dev/null
    ports:
    - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  neo4j:
    image: neo4j:3.5.0
    ports:
    - 7474:7474
    - 7687:7687
    volumes:
    - ./plugins:/plugins
    environment:
    - NEO4J_AUTH=neo4j/neo
    - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*