resultsDir: /root/results
sshKeyPath: /root/.ssh/g_compute_engine
sshUsername: filip
infrastructureProvider:
  name: Google Cloud Platform
  projectId: modular-citron-220321
  serviceAccountKeyFilename: /input/modular-citron-220321-2a8dd4b4b93f.json
  zoneName: europe-west1-b