resultsDir: ../experiments/results
sshKeyPath: /home/filip/.ssh/gcloudkey
sshUsername: filip
infrastructureProvider:
  name: Google Cloud Platform
  projectId: modular-citron-220321
  serviceAccountKeyFilename: /home/filip/Desktop/modular-citron-220321-2a8dd4b4b93f.json
  zoneName: europe-west1-b